service: todo-serverless

frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  
  environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  
  iam:
    role:
      statements:	
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: '*'
        - Effect: Allow
          Action: 's3:*'
          Resource: '*'

package:
  individually: true
  include:
    - './src/templates/**'

functions:
  create-task:
    handler: 'src/functions/createTask.handler'
    events:
      - http:
          path: 'task'
          method: 'post'
          cors: true
  
  update-task-status:
    handler: 'src/functions/updateTaskStatus.handler'
    events:
      - http:
          path: 'task/{id}/status/{status}'
          method: 'patch'
          cors: true

  list-tasks:
    handler: 'src/functions/listTasks.handler'
    events:
      - http:
          path: 'tasks'
          method: 'get'
          cors: true
  
  delete-task:
    handler: 'src/functions/deleteTask.handler'
    events:
      - http:
          path: 'task/{id}'
          method: 'delete'
          cors: true
  
  export-tasks-to-pdf:
    handler: 'src/functions/exportTasksToPdf.handler'
    events:
      - http:
          path: 'tasks/export/pdf'
          method: 'get'
          cors: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    external: 
      - 'puppeteer'
    exclude: 
      - 'aws-sdk'
      - 'node_modules'
    target: 'node14'
    define:
      'require.resolve': undefined
    platform: 'node'
    concurrency: 10
  dynamodb:
    stages: 
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    dbCertificateUsers:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: tasks
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
